//! Persisted configuration (settings + profiles).
//!
//! On disk: `<config_dir>/MonitorBrightnessControl/{settings,profiles}.toml`.

use std::fs;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

const APP_DIR_NAME: &str = "MonitorBrightnessControl";

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Settings {
    /// Default per-monitor brightness applied at startup. Map of monitor id
    /// → percentage (0..=100). Missing entries leave the monitor untouched.
    pub initial_brightness: std::collections::BTreeMap<String, u8>,

    /// Hotkey bindings (Tauri shortcut strings, e.g. `"CommandOrControl+Shift+Up"`).
    pub hotkeys: HotkeySettings,

    /// Auto-dim configuration. Disabled by default until the user provides
    /// coordinates.
    pub auto_dim: AutoDimSettings,

    /// Multi-monitor brightness sync. When enabled, the application keeps
    /// every monitor brightness offset by `sync_offsets[id]` (signed) from
    /// the primary one.
    pub sync_enabled: bool,
    pub sync_primary_id: Option<String>,
    pub sync_offsets: std::collections::BTreeMap<String, i8>,

    /// User-defined time-of-day brightness rules. Evaluated against the
    /// system's local timezone every minute.
    pub schedules: ScheduleSettings,

    /// Rolling backups of `settings.toml`.
    pub backup: BackupSettings,

    /// UI language. `"auto"` = follow OS locale, otherwise an ISO 639-1
    /// code like `"en"`, `"de"`, `"es"`, `"fr"`, `"it"`, `"ja"`.
    pub language: String,
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            initial_brightness: Default::default(),
            hotkeys: HotkeySettings::default(),
            auto_dim: AutoDimSettings::default(),
            sync_enabled: false,
            sync_primary_id: None,
            sync_offsets: Default::default(),
            schedules: ScheduleSettings::default(),
            backup: BackupSettings::default(),
            language: "auto".into(),
        }
    }
}

/// Configuration for the rolling backup of `settings.toml`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct BackupSettings {
    /// When enabled, every `save_settings` snapshots the previous on-disk
    /// `settings.toml` into the `backups/` folder before overwriting it.
    pub enabled: bool,
    /// Number of newest backups to keep. Older ones are pruned on every save
    /// and on every explicit "back up now". Clamped to at least 1.
    pub retention: u32,
}

impl Default for BackupSettings {
    fn default() -> Self {
        Self {
            enabled: true,
            retention: 10,
        }
    }
}

/// Metadata about a single backup file, returned to the frontend.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BackupInfo {
    /// Which config file this snapshots: `"settings"` or `"profiles"`.
    pub kind: String,
    /// Base file name within the backups directory, e.g.
    /// `settings-1717000000000.toml`. Never contains a path separator.
    pub file_name: String,
    /// Creation time in Unix milliseconds, parsed from the file name (falls
    /// back to the filesystem mtime if the name is unexpected).
    pub created_unix_ms: u64,
    /// File size in bytes.
    pub size_bytes: u64,
}

/// Container for time-of-day brightness rules.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ScheduleSettings {
    /// Master switch — disabling this freezes every entry without losing
    /// the configuration.
    pub enabled: bool,
    pub items: Vec<ScheduleEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ScheduleEntry {
    /// Stable identifier — autogenerated at creation time.
    pub id: String,
    /// Human-friendly label. Optional, falls back to the time string in the UI.
    pub name: String,
    pub enabled: bool,
    /// `HH:MM` 24-hour, interpreted in the system's local timezone.
    pub time: String,
    /// Weekdays the rule fires on, encoded as 0=Sunday … 6=Saturday. An
    /// empty vector means "every day".
    pub days: Vec<u8>,
    /// Monitor ids the rule affects. Empty vector = every connected monitor.
    pub monitor_ids: Vec<String>,
    /// Target brightness in 0..=100.
    pub brightness_percent: u8,
}

impl Default for ScheduleEntry {
    fn default() -> Self {
        Self {
            id: String::new(),
            name: String::new(),
            enabled: true,
            time: "08:00".into(),
            days: vec![0, 1, 2, 3, 4, 5, 6],
            monitor_ids: Vec::new(),
            brightness_percent: 80,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct HotkeySettings {
    /// Step up brightness by `step_percent` on every monitor.
    pub brightness_up: Option<String>,
    pub brightness_down: Option<String>,
    /// Toggle "night mode" — drop to `night_brightness_percent`.
    pub toggle_night: Option<String>,
    /// Show / hide the main window.
    pub toggle_window: Option<String>,
    /// Quick mute (sets all displays to 0%).
    pub blackout: Option<String>,

    pub step_percent: f32,
    pub night_brightness_percent: f32,
}

impl Default for HotkeySettings {
    fn default() -> Self {
        Self {
            brightness_up: Some("CommandOrControl+Shift+Up".into()),
            brightness_down: Some("CommandOrControl+Shift+Down".into()),
            toggle_night: Some("CommandOrControl+Shift+N".into()),
            toggle_window: Some("CommandOrControl+Shift+B".into()),
            blackout: None,
            step_percent: 5.0,
            night_brightness_percent: 15.0,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct AutoDimSettings {
    pub enabled: bool,
    pub latitude: f64,
    pub longitude: f64,
    pub day_brightness: u8,
    pub night_brightness: u8,
    /// Transition duration in minutes around sunrise/sunset.
    pub transition_minutes: u32,
}

impl Default for AutoDimSettings {
    fn default() -> Self {
        Self {
            enabled: false,
            latitude: 0.0,
            longitude: 0.0,
            day_brightness: 80,
            night_brightness: 25,
            transition_minutes: 30,
        }
    }
}

/// Profiles the user can attach to executables / bundle ids.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Profiles {
    pub items: Vec<Profile>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Profile {
    /// Unique identifier — autogenerated at creation time.
    pub id: String,
    /// User-facing display name.
    pub name: String,
    /// Application identifier the OS reports for foreground windows.
    /// On Windows this is the basename of the executable, on macOS the
    /// bundle identifier, on Linux the WM_CLASS value (instance).
    pub app_id: String,
    /// Per-monitor overrides applied while this app is focused. Keys are
    /// monitor ids; missing monitors are left untouched.
    pub monitors: std::collections::BTreeMap<String, ProfileMonitorSettings>,
    /// Legacy field from earlier versions — kept so existing profiles
    /// continue to load. Migrated into `monitors` on save.
    #[serde(skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    pub brightness: std::collections::BTreeMap<String, u8>,
}

impl Default for Profile {
    fn default() -> Self {
        Self {
            id: String::new(),
            name: String::new(),
            app_id: String::new(),
            monitors: Default::default(),
            brightness: Default::default(),
        }
    }
}

/// Per-monitor override block. Any field set to `None` means "leave the
/// monitor's current value alone".
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ProfileMonitorSettings {
    /// Brightness percentage 0..=100.
    pub brightness: Option<u8>,
    /// Contrast as a percentage 0..=100 of the monitor's VCP max for code
    /// 0x12. Resolved into an absolute VCP value at apply time so the
    /// stored profile is portable across monitors with different maxima.
    pub contrast: Option<u8>,
    /// Raw VCP value for code 0x14 (color preset / temperature). Values
    /// the UI exposes today: 1=sRGB, 2=Native, 4=5000K, 5=6500K, 6=7500K,
    /// 8=9300K, 11=User.
    pub color_preset: Option<u16>,
}

pub fn config_dir() -> PathBuf {
    dirs::config_dir()
        .map(|p| p.join(APP_DIR_NAME))
        .unwrap_or_else(|| PathBuf::from(".").join(APP_DIR_NAME))
}

fn settings_path() -> PathBuf {
    config_dir().join("settings.toml")
}

fn profiles_path() -> PathBuf {
    config_dir().join("profiles.toml")
}

pub fn load_settings() -> Settings {
    let path = settings_path();
    let raw = match fs::read_to_string(&path) {
        Ok(s) => s,
        Err(_) => return Settings::default(),
    };
    match toml::from_str::<Settings>(&raw) {
        Ok(s) => s,
        Err(e) => {
            log::warn!("settings.toml parse error: {e}; using defaults");
            Settings::default()
        }
    }
}

pub fn save_settings(s: &Settings) -> std::io::Result<()> {
    let dir = config_dir();
    fs::create_dir_all(&dir)?;

    // Snapshot the previous on-disk settings before we overwrite them. We do
    // this when backups are enabled, or unconditionally when no backup exists
    // yet (so the very first save preserves the original configuration).
    let path = settings_path();
    if path.exists() {
        let want_backup = s.backup.enabled || list_backups().is_empty();
        if want_backup {
            if let Err(e) = create_backup_from(&path, "settings") {
                log::warn!("settings backup failed: {e}");
            }
            prune_backups(s.backup.retention);
        }
    }

    let raw = toml::to_string_pretty(s).map_err(|e| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, format!("toml encode: {e}"))
    })?;
    let tmp = path.with_extension("toml.tmp");
    fs::write(&tmp, raw)?;
    fs::rename(&tmp, &path)?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Settings backups
// ---------------------------------------------------------------------------

fn backups_dir() -> PathBuf {
    config_dir().join("backups")
}

fn unix_millis_now() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

/// Strip a known backup prefix (`settings-` or `profiles-`), returning the rest
/// and the kind. `None` if the name doesn't start with a recognised prefix.
fn split_backup_name(file_name: &str) -> Option<(&'static str, &str)> {
    if let Some(rest) = file_name.strip_prefix("settings-") {
        Some(("settings", rest))
    } else {
        file_name
            .strip_prefix("profiles-")
            .map(|rest| ("profiles", rest))
    }
}

/// Validate that `file_name` is a plain backup file name with no path
/// components, matching `<settings|profiles>-<digits>.toml`. Prevents path
/// traversal in restore/delete commands.
fn is_valid_backup_name(file_name: &str) -> bool {
    if file_name.contains('/') || file_name.contains('\\') || file_name.contains("..") {
        return false;
    }
    match split_backup_name(file_name).and_then(|(_, r)| r.strip_suffix(".toml")) {
        Some(stamp) => !stamp.is_empty() && stamp.bytes().all(|b| b.is_ascii_digit()),
        None => false,
    }
}

fn parse_stamp(file_name: &str) -> Option<u64> {
    split_backup_name(file_name)
        .and_then(|(_, r)| r.strip_suffix(".toml"))
        .and_then(|s| s.parse::<u64>().ok())
}

/// Copy `source` into the backups directory under a timestamped name. `prefix`
/// is `"settings"` or `"profiles"`.
fn create_backup_from(source: &std::path::Path, prefix: &str) -> std::io::Result<BackupInfo> {
    let dir = backups_dir();
    fs::create_dir_all(&dir)?;
    let mut stamp = unix_millis_now();
    let mut file_name = format!("{prefix}-{stamp}.toml");
    // Avoid colliding with an existing backup taken in the same millisecond.
    while dir.join(&file_name).exists() {
        stamp += 1;
        file_name = format!("{prefix}-{stamp}.toml");
    }
    let dest = dir.join(&file_name);
    fs::copy(source, &dest)?;
    let size_bytes = fs::metadata(&dest).map(|m| m.len()).unwrap_or(0);
    Ok(BackupInfo {
        kind: prefix.to_string(),
        file_name,
        created_unix_ms: stamp,
        size_bytes,
    })
}

/// Ensure at least one backup exists. Called once at program start so the
/// user's original configuration is always preserved — even before the first
/// manual save and regardless of the `backup.enabled` toggle. No-op if a
/// backup already exists.
pub fn ensure_initial_backup() {
    let existing = list_backups();
    let have = |kind: &str| existing.iter().any(|b| b.kind == kind);

    // Settings: guarantee the original configuration is snapshotted, writing
    // the defaults first if no file exists yet (settings always have a
    // meaningful default).
    if !have("settings") {
        if !settings_path().exists() {
            if let Err(e) = save_settings(&load_settings()) {
                log::warn!("initial settings write failed: {e}");
            }
        }
        if settings_path().exists() {
            match create_backup_from(&settings_path(), "settings") {
                Ok(info) => log::info!("created initial settings backup {}", info.file_name),
                Err(e) => log::warn!("initial settings backup failed: {e}"),
            }
        }
    }

    // Profiles: snapshot only when the user already has a profiles file —
    // there's nothing to preserve otherwise.
    if !have("profiles") && profiles_path().exists() {
        match create_backup_from(&profiles_path(), "profiles") {
            Ok(info) => log::info!("created initial profiles backup {}", info.file_name),
            Err(e) => log::warn!("initial profiles backup failed: {e}"),
        }
    }
}

/// Take a backup of the current settings (and profiles, if present) on demand.
/// Returns the new entries.
pub fn backup_now() -> std::io::Result<Vec<BackupInfo>> {
    if !settings_path().exists() {
        // Nothing saved yet — persist defaults first so there is something to
        // snapshot, then back that up.
        save_settings(&load_settings())?;
    }
    let mut out = vec![create_backup_from(&settings_path(), "settings")?];
    if profiles_path().exists() {
        out.push(create_backup_from(&profiles_path(), "profiles")?);
    }
    // Respect retention even for manual backups.
    let retention = load_settings().backup.retention;
    prune_backups(retention);
    Ok(out)
}

/// List existing backups, newest first.
pub fn list_backups() -> Vec<BackupInfo> {
    let dir = backups_dir();
    let mut out = Vec::new();
    let entries = match fs::read_dir(&dir) {
        Ok(e) => e,
        Err(_) => return out,
    };
    for entry in entries.flatten() {
        let name = match entry.file_name().into_string() {
            Ok(n) => n,
            Err(_) => continue,
        };
        if !is_valid_backup_name(&name) {
            continue;
        }
        let kind = split_backup_name(&name)
            .map(|(k, _)| k.to_string())
            .unwrap_or_default();
        let meta = entry.metadata().ok();
        let size_bytes = meta.as_ref().map(|m| m.len()).unwrap_or(0);
        let created_unix_ms = parse_stamp(&name).unwrap_or(0);
        out.push(BackupInfo {
            kind,
            file_name: name,
            created_unix_ms,
            size_bytes,
        });
    }
    out.sort_by(|a, b| b.created_unix_ms.cmp(&a.created_unix_ms));
    out
}

/// Delete the oldest backups so that at most `retention` of **each kind**
/// (settings, profiles) remain.
pub fn prune_backups(retention: u32) {
    let keep = retention.max(1) as usize;
    let backups = list_backups(); // newest first, mixed kinds
    let dir = backups_dir();
    for kind in ["settings", "profiles"] {
        for old in backups.iter().filter(|b| b.kind == kind).skip(keep) {
            let p = dir.join(&old.file_name);
            if let Err(e) = fs::remove_file(&p) {
                log::warn!("pruning backup {}: {e}", old.file_name);
            }
        }
    }
}

/// Delete a single backup by file name. Rejects names that are not plain
/// backup files.
pub fn delete_backup(file_name: &str) -> std::io::Result<()> {
    if !is_valid_backup_name(file_name) {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "invalid backup name",
        ));
    }
    fs::remove_file(backups_dir().join(file_name))
}

/// Restore a backup: parse it, make a safety backup of the current settings,
/// then write the restored settings as the active configuration. Returns the
/// restored [`Settings`].
pub fn restore_backup(file_name: &str) -> std::io::Result<Settings> {
    if !is_valid_backup_name(file_name) || !file_name.starts_with("settings-") {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "invalid settings backup name",
        ));
    }
    let src = backups_dir().join(file_name);
    let raw = fs::read_to_string(&src)?;
    let restored: Settings = toml::from_str(&raw).map_err(|e| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("backup parse error: {e}"),
        )
    })?;
    // save_settings will snapshot the current file before overwriting, so the
    // pre-restore state is itself recoverable.
    save_settings(&restored)?;
    Ok(restored)
}

/// Restore a profiles backup: parse it, snapshot the current profiles (via
/// save_profiles), then write the restored profiles as active. Returns them.
pub fn restore_profiles(file_name: &str) -> std::io::Result<Profiles> {
    if !is_valid_backup_name(file_name) || !file_name.starts_with("profiles-") {
        return Err(std::io::Error::new(
            std::io::ErrorKind::InvalidInput,
            "invalid profiles backup name",
        ));
    }
    let src = backups_dir().join(file_name);
    let raw = fs::read_to_string(&src)?;
    let restored: Profiles = toml::from_str(&raw).map_err(|e| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            format!("backup parse error: {e}"),
        )
    })?;
    save_profiles(&restored)?;
    Ok(restored)
}

pub fn load_profiles() -> Profiles {
    let path = profiles_path();
    let raw = match fs::read_to_string(&path) {
        Ok(s) => s,
        Err(_) => return Profiles::default(),
    };
    match toml::from_str::<Profiles>(&raw) {
        Ok(p) => p,
        Err(e) => {
            log::warn!("profiles.toml parse error: {e}; using defaults");
            Profiles::default()
        }
    }
}

pub fn save_profiles(p: &Profiles) -> std::io::Result<()> {
    let dir = config_dir();
    fs::create_dir_all(&dir)?;

    // Snapshot the previous profiles before overwriting, mirroring the settings
    // backup behaviour. The backup toggle lives in settings, so honour that —
    // or take one regardless when no backup exists yet.
    let path = profiles_path();
    if path.exists() {
        let backup = load_settings().backup;
        if backup.enabled || list_backups().is_empty() {
            if let Err(e) = create_backup_from(&path, "profiles") {
                log::warn!("profiles backup failed: {e}");
            }
            prune_backups(backup.retention);
        }
    }

    let raw = toml::to_string_pretty(p).map_err(|e| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, format!("toml encode: {e}"))
    })?;
    let tmp = path.with_extension("toml.tmp");
    fs::write(&tmp, raw)?;
    fs::rename(&tmp, &path)?;
    Ok(())
}
