//! Persisted configuration (settings + profiles).
//!
//! On disk: `<config_dir>/MonitorBrightnessControl/{settings,profiles}.toml`.

use std::fs;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

const APP_DIR_NAME: &str = "MonitorBrightnessControl";

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Settings {
    /// Default per-monitor brightness applied at startup. Map of monitor id
    /// → percentage (0..=100). Missing entries leave the monitor untouched.
    pub initial_brightness: std::collections::BTreeMap<String, u8>,

    /// Hotkey bindings (Tauri shortcut strings, e.g. `"CommandOrControl+Shift+Up"`).
    pub hotkeys: HotkeySettings,

    /// Auto-dim configuration. Disabled by default until the user provides
    /// coordinates.
    pub auto_dim: AutoDimSettings,

    /// Multi-monitor brightness sync. When enabled, the application keeps
    /// every monitor brightness offset by `sync_offsets[id]` (signed) from
    /// the primary one.
    pub sync_enabled: bool,
    pub sync_primary_id: Option<String>,
    pub sync_offsets: std::collections::BTreeMap<String, i8>,

    /// User-defined time-of-day brightness rules. Evaluated against the
    /// system's local timezone every minute.
    pub schedules: ScheduleSettings,

    /// UI language. `"auto"` = follow OS locale, otherwise an ISO 639-1
    /// code like `"en"`, `"de"`, `"es"`, `"fr"`, `"it"`, `"ja"`.
    pub language: String,
}

impl Default for Settings {
    fn default() -> Self {
        Self {
            initial_brightness: Default::default(),
            hotkeys: HotkeySettings::default(),
            auto_dim: AutoDimSettings::default(),
            sync_enabled: false,
            sync_primary_id: None,
            sync_offsets: Default::default(),
            schedules: ScheduleSettings::default(),
            language: "auto".into(),
        }
    }
}

/// Container for time-of-day brightness rules.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ScheduleSettings {
    /// Master switch — disabling this freezes every entry without losing
    /// the configuration.
    pub enabled: bool,
    pub items: Vec<ScheduleEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ScheduleEntry {
    /// Stable identifier — autogenerated at creation time.
    pub id: String,
    /// Human-friendly label. Optional, falls back to the time string in the UI.
    pub name: String,
    pub enabled: bool,
    /// `HH:MM` 24-hour, interpreted in the system's local timezone.
    pub time: String,
    /// Weekdays the rule fires on, encoded as 0=Sunday … 6=Saturday. An
    /// empty vector means "every day".
    pub days: Vec<u8>,
    /// Monitor ids the rule affects. Empty vector = every connected monitor.
    pub monitor_ids: Vec<String>,
    /// Target brightness in 0..=100.
    pub brightness_percent: u8,
}

impl Default for ScheduleEntry {
    fn default() -> Self {
        Self {
            id: String::new(),
            name: String::new(),
            enabled: true,
            time: "08:00".into(),
            days: vec![0, 1, 2, 3, 4, 5, 6],
            monitor_ids: Vec::new(),
            brightness_percent: 80,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct HotkeySettings {
    /// Step up brightness by `step_percent` on every monitor.
    pub brightness_up: Option<String>,
    pub brightness_down: Option<String>,
    /// Toggle "night mode" — drop to `night_brightness_percent`.
    pub toggle_night: Option<String>,
    /// Show / hide the main window.
    pub toggle_window: Option<String>,
    /// Quick mute (sets all displays to 0%).
    pub blackout: Option<String>,

    pub step_percent: f32,
    pub night_brightness_percent: f32,
}

impl Default for HotkeySettings {
    fn default() -> Self {
        Self {
            brightness_up: Some("CommandOrControl+Shift+Up".into()),
            brightness_down: Some("CommandOrControl+Shift+Down".into()),
            toggle_night: Some("CommandOrControl+Shift+N".into()),
            toggle_window: Some("CommandOrControl+Shift+B".into()),
            blackout: None,
            step_percent: 5.0,
            night_brightness_percent: 15.0,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct AutoDimSettings {
    pub enabled: bool,
    pub latitude: f64,
    pub longitude: f64,
    pub day_brightness: u8,
    pub night_brightness: u8,
    /// Transition duration in minutes around sunrise/sunset.
    pub transition_minutes: u32,
}

impl Default for AutoDimSettings {
    fn default() -> Self {
        Self {
            enabled: false,
            latitude: 0.0,
            longitude: 0.0,
            day_brightness: 80,
            night_brightness: 25,
            transition_minutes: 30,
        }
    }
}

/// Profiles the user can attach to executables / bundle ids.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Profiles {
    pub items: Vec<Profile>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Profile {
    /// Unique identifier — autogenerated at creation time.
    pub id: String,
    /// User-facing display name.
    pub name: String,
    /// Application identifier the OS reports for foreground windows.
    /// On Windows this is the basename of the executable, on macOS the
    /// bundle identifier, on Linux the WM_CLASS value (instance).
    pub app_id: String,
    /// Per-monitor overrides applied while this app is focused. Keys are
    /// monitor ids; missing monitors are left untouched.
    pub monitors: std::collections::BTreeMap<String, ProfileMonitorSettings>,
    /// Legacy field from earlier versions — kept so existing profiles
    /// continue to load. Migrated into `monitors` on save.
    #[serde(skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    pub brightness: std::collections::BTreeMap<String, u8>,
}

impl Default for Profile {
    fn default() -> Self {
        Self {
            id: String::new(),
            name: String::new(),
            app_id: String::new(),
            monitors: Default::default(),
            brightness: Default::default(),
        }
    }
}

/// Per-monitor override block. Any field set to `None` means "leave the
/// monitor's current value alone".
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ProfileMonitorSettings {
    /// Brightness percentage 0..=100.
    pub brightness: Option<u8>,
    /// Contrast as a percentage 0..=100 of the monitor's VCP max for code
    /// 0x12. Resolved into an absolute VCP value at apply time so the
    /// stored profile is portable across monitors with different maxima.
    pub contrast: Option<u8>,
    /// Raw VCP value for code 0x14 (color preset / temperature). Values
    /// the UI exposes today: 1=sRGB, 2=Native, 4=5000K, 5=6500K, 6=7500K,
    /// 8=9300K, 11=User.
    pub color_preset: Option<u16>,
}

pub fn config_dir() -> PathBuf {
    dirs::config_dir()
        .map(|p| p.join(APP_DIR_NAME))
        .unwrap_or_else(|| PathBuf::from(".").join(APP_DIR_NAME))
}

fn settings_path() -> PathBuf {
    config_dir().join("settings.toml")
}

fn profiles_path() -> PathBuf {
    config_dir().join("profiles.toml")
}

pub fn load_settings() -> Settings {
    let path = settings_path();
    let raw = match fs::read_to_string(&path) {
        Ok(s) => s,
        Err(_) => return Settings::default(),
    };
    match toml::from_str::<Settings>(&raw) {
        Ok(s) => s,
        Err(e) => {
            log::warn!("settings.toml parse error: {e}; using defaults");
            Settings::default()
        }
    }
}

pub fn save_settings(s: &Settings) -> std::io::Result<()> {
    let dir = config_dir();
    fs::create_dir_all(&dir)?;
    let raw = toml::to_string_pretty(s).map_err(|e| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, format!("toml encode: {e}"))
    })?;
    let tmp = settings_path().with_extension("toml.tmp");
    fs::write(&tmp, raw)?;
    fs::rename(&tmp, settings_path())?;
    Ok(())
}

pub fn load_profiles() -> Profiles {
    let path = profiles_path();
    let raw = match fs::read_to_string(&path) {
        Ok(s) => s,
        Err(_) => return Profiles::default(),
    };
    match toml::from_str::<Profiles>(&raw) {
        Ok(p) => p,
        Err(e) => {
            log::warn!("profiles.toml parse error: {e}; using defaults");
            Profiles::default()
        }
    }
}

pub fn save_profiles(p: &Profiles) -> std::io::Result<()> {
    let dir = config_dir();
    fs::create_dir_all(&dir)?;
    let raw = toml::to_string_pretty(p).map_err(|e| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, format!("toml encode: {e}"))
    })?;
    let tmp = profiles_path().with_extension("toml.tmp");
    fs::write(&tmp, raw)?;
    fs::rename(&tmp, profiles_path())?;
    Ok(())
}
